name: Update README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MMESHBOT }}
        with:
          template: "templates/profile.md.tpl"
          writeTo: "profile/README.md"
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.MMESHBOT }}
        with:
          commit_message: "docs: update generated README"
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
